name: API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Check if the question-service directory exists
            if [ -d "question-service" ]; then
              echo "Repository exists. Pulling latest changes..."
              cd question-service
              git pull origin main
            else
              echo "Repository does not exist. Cloning repository..."
              git clone git@github.com:TestPlatformService/question-service.git
              cd question-service
            fi

            # Stop and remove existing Docker containers
            if sudo docker compose ps -q | grep -q .; then
              echo "Stopping and removing existing containers..."
              sudo docker compose down
            else
              echo "No existing containers to stop."
            fi

            # Build and start Docker containers
            echo "Building and starting Docker containers..."
            sudo docker compose up -d --build
